name: tic_tac_toe # Noughts game
description: >-
  Tic-tac-toe is a game that is traditionally played by being drawn on paper

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Icons for IOS
  cupertino_icons: ^1.0.2

  #
  web_socket_channel: ^2.1.0

  #
  get_it: ^7.2.0

  #
  audioplayers: ^0.20.1
  # just_audio: ^0.9.11

  # ReaxtiveX Dart. Provides extra features to Dart's streams
  rxdart: ^0.27.2

  #
  intl: ^0.17.0

  #
  animated_text_kit: ^4.2.1

  # Supplies the app version details e.g. build name/number
  # package_info: ">=0.4.1 <2.0.0"

  # Shares in app content using respective system sharing APIs
  # share: ^0.6.5+4

  # Opens urls in the phone browser
  # url_launcher: ^5.4.10

  # Official animations package providing Material Design transitions
  # animations: ^1.1.2
  # simple_animations: ^2.2.3

  #
  logger: ^1.1.0
  animations: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # Splash screen generator
  flutter_native_splash: ^1.2.3

# Settings for the flutter_native_splash package
# run flutter pub run flutter_native_splash:create to update splash screen
flutter_native_splash:
  image: assets/images/logo.png
  color: "#FFFFFF"
  ios: false
  web: false

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Defines files available to the app
  assets:
    - assets/
    - assets/images/
    - assets/sound/
    - assets/google_fonts/

  # Enable generation of localized Strings from arb files
  generate: true

  # Specifies fonts and their respective font weights (thickness)
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/google_fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Nunito-Black.ttf
          weight: 900
